apiVersion: v1
data:
  .dockercfg: eyAiaHR0cHM6Ly9yZWdkYi5zeW5pc3lzLmNvbSI6IHsgImF1dGgiOiAiYzI1aGNITm9iM1J6ZG1NNmMyNWhjSE5vYjNSemRtTT0iLCAiZW1haWwiOiAibnVsbCIgfSB9
kind: Secret
metadata:
  creationTimestamp: null
  name: regdb.synisys.com
type: kubernetes.io/dockercfg
