apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authservice
    load-balancer-authservice-v1: "true"
  name: authservice-v1
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: authservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: authservice
        load-balancer-authservice-v1: "true"
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Dconsul.host=consul
        - name: certificateKey
          valueFrom:
            secretKeyRef:
              key: auth.service.certificate
              name: services-certification-keys
        image: nginx
        imagePullPolicy: IfNotPresent
        name: authservice-v1
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: vault
      serviceAccountName: vault
      terminationGracePeriodSeconds: 30
