apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8899"
    prometheus.io/scrape: "true"
  name: authservice-v1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8899
  selector:
    load-balancer-authservice-v1: "true"
  sessionAffinity: None
  type: ClusterIP
